## Numpy Practice

In [3]:
!pip install numpy

In [4]:
import numpy as np

#### Difference between numpy array and list

In [5]:
#list
lst=[1,2,3,4]
print(type(lst))
print(lst)

<class 'list'>
[1, 2, 3, 4]


In [6]:
#numpy array
a=np.array([1,2,3,4])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [7]:
#numpy array is homogenous
import numpy as np
arr = np.array([1, 2, 3])  
print(arr.dtype) 
arr_float = np.array([1.0, 2.5, 3.7])  
print(arr_float.dtype) 
arr_mixed = np.array([1, 2.5, 3])  
print(arr_mixed.dtype)  

int32
float64
float64


In [9]:
import numpy as np
arr_mixed = np.array([1, 2.5, "hello"])  # Elements are promoted to dtype='<U32' (unicode string)
print(arr_mixed.dtype) 
print(arr_mixed)  

<U32
['1' '2.5' 'hello']


In [10]:
%%time
b=np.arange(100)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
CPU times: total: 0 ns
Wall time: 2.02 ms


In [13]:
%%time

lst = list(range(1000000));

for i in range(1000000):
    lst[i] *= lst[i];

CPU times: total: 297 ms
Wall time: 356 ms


In [14]:
%%time

arr = np.arange(1000000)

arr = arr * arr

CPU times: total: 0 ns
Wall time: 5.19 ms


### Numpy attributes/properties

In [15]:
#dtype
arr=np.array([[1,2,3],[4,5,6]])
print(arr.dtype)

int32


In [16]:
#shape
print(arr.shape)

(2, 3)


In [17]:
#size
print(arr.size)

6


In [22]:
a=np.array([[1.0,2.5],[2.3,9.9]])
print(a)
print(a.itemsize)

[[1.  2.5]
 [2.3 9.9]]
8


In [18]:
#itemsize
print(arr.itemsize)

4


In [19]:
#ndim
print(arr.ndim)

2


### Functions for creating numpy array

In [24]:
#array
a=np.array((1,2,3,4))
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [27]:
#zeros
b=np.zeros((3,4))
print(type(b))
print(b)
print(b.itemsize)
print(b.dtype)

<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
8
float64


In [28]:
#ones
c=np.ones((2,3))
print(type(c))
print(c)
print(c.itemsize)
print(c.dtype)

<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]
8
float64


In [29]:
#full
d=np.full((3,4),7)
print(d)
print(d.dtype)
print(d.itemsize)
print(type(d))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
int32
4
<class 'numpy.ndarray'>


In [34]:
#empty
import numpy as np 
d = np.empty((2, 3))  # Create a 2x3 uninitialized array
print(arr5)
print(d.dtype)
print(d.itemsize)

[[1. 1. 1.]
 [1. 1. 1.]]
float64
8


In [36]:
#eye or identity
import numpy as np
arr8 = np.eye(3)  
print(arr8)
import numpy as np
arr9 = np.identity(3)  # Create a 3x3 identity matrix
print(arr9)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#arange
d=np.arange(10)
e=np.arange(1,10)
f=np.arange(1,10,2)
print(d,e,f)

[0 1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9] [1 3 5 7 9]


## Datatypes in numpy

* Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* str - string
* f - float
* m - timedelta
* M - datetime
* O - object
* u - unsigned integer
* c - complex float
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [37]:
import numpy as np
arr = np.array([2, 1, 4, 5], dtype='f')
print("Array: \n", arr)
# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2. 1. 4. 5.]
Data Type:  float32


In [38]:
import numpy as np
arr = np.array([2, 1, 4, 5], dtype='O')
print("Array: \n", arr)
# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2 1 4 5]
Data Type:  object


In [39]:
import numpy as np
arr = np.array([2, 1, 4, 5], dtype='str')
print("Array: \n", arr)
# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 ['2' '1' '4' '5']
Data Type:  <U1


In [40]:
import numpy as np
arr = np.array([2, 1, 4, 5], dtype='i')
print("Array: \n", arr)
# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2 1 4 5]
Data Type:  int32


### Numpy Random numbers

In [46]:
#random.rand
a=np.random.rand(10)
print(a)
print(a.dtype)
print(type(a))

[0.33973069 0.77172731 0.10006906 0.34826445 0.75275043 0.43844515
 0.92839579 0.97258019 0.36714918 0.0441451 ]
float64
<class 'numpy.ndarray'>


In [47]:
#random.randn
b=np.random.randn(10)
print(b)
print(b.dtype)
print(type(b))

[-2.26825668  0.27140628  0.64511346  0.94976523 -0.91181128 -0.54838571
 -0.00586076 -0.27839798 -0.10541464  0.30420992]
float64
<class 'numpy.ndarray'>


In [49]:
#random.uniform
c=np.random.uniform(10)
print(c)
print(type(c))

3.590212019205225
<class 'float'>


In [50]:
c=np.random.uniform(10,20,size=(3,4))
print(c)
print(type(c))

[[17.76271244 13.59260538 16.80652237 17.35350725]
 [16.16011154 10.99385748 16.51305959 18.84339834]
 [12.1465485  18.18305388 17.35934893 12.2065112 ]]
<class 'numpy.ndarray'>


In [51]:
#random.randint
c=np.random.randint(10)
print(c)
print(type(c))

1
<class 'int'>


In [52]:
c=np.random.randint(10,20,size=(5,6))
print(c)
print(type(c))

[[15 19 19 19 14 15]
 [10 18 11 11 15 11]
 [12 15 18 14 14 11]
 [17 17 13 18 19 12]
 [19 14 10 11 12 10]]
<class 'numpy.ndarray'>


### Indexing,slicing,updating

In [4]:
#for multi-dimensional array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2])  
print(arr[1][2])

6
6


In [7]:
#for single dimensional
a=np.array((1,2,3))
print(a[1])
print(a[3])

2


IndexError: index 3 is out of bounds for axis 0 with size 3

In [6]:
#negative indexing
print(a[-1])

3


In [61]:
#slicing
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:2, 1:])  
arr = np.array([1, 2, 3, 4, 5])
print(arr[::2])  # Slice every second element

[[2 3]
 [5 6]]
[1 3 5]


In [62]:
# Randomly generating 1 dimensional array
import numpy as np
arr = np.random.randint(100, size = (10, ))
print("Numpy Array: \n", arr)
print("Shape: ", arr.shape)

Numpy Array: 
 [ 0 67 34 28  4 23 66 69 58 80]
Shape:  (10,)


In [63]:
idx = [True, False, False, False, False, True, False, False, True, True]
print(arr[idx])

[ 0 23 58 80]


In [64]:
#updating
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr[0] = 10  # Update the first element to 10
print(arr)

[10  2  3  4  5]


In [65]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = [20, 30, 40]  # Update elements from index 1 to 3
print(arr)

[ 1 20 30 40  5]


In [66]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1] = 10  # Update element at row 0, column 1 to 10
print(arr)

[[ 1 10  3]
 [ 4  5  6]]


In [28]:
#flatten,ravel
a=np.random.randint(1,20,size=(3,4))
print(a)

[[ 9 15 17 11]
 [ 1  7 14  1]
 [ 3 11 14  2]]


In [29]:
b=a.flatten()
print(b)
print(b.shape)

[ 9 15 17 11  1  7 14  1  3 11 14  2]
(12,)


In [30]:
#ravel
c=a.ravel()
print(c)
print(c.shape)

[ 9 15 17 11  1  7 14  1  3 11 14  2]
(12,)


In [31]:
print("original:",a)


original: [[ 9 15 17 11]
 [ 1  7 14  1]
 [ 3 11 14  2]]


In [32]:
a[1,1]=20
print("updated:",a)

updated: [[ 9 15 17 11]
 [ 1 20 14  1]
 [ 3 11 14  2]]


In [33]:
print(b)
print(c)

[ 9 15 17 11  1  7 14  1  3 11 14  2]
[ 9 15 17 11  1 20 14  1  3 11 14  2]


In [34]:
#reshape
arr=np.random.randint(1,10,size=(5,4))
print(arr)


[[7 2 7 5]
 [9 9 2 1]
 [4 2 2 7]
 [1 7 2 5]
 [1 5 6 6]]


In [36]:
arr1=np.reshape(arr,(4,5))
arr1

array([[7, 2, 7, 5, 9],
       [9, 2, 1, 4, 2],
       [2, 7, 1, 7, 2],
       [5, 1, 5, 6, 6]])

In [38]:
arr2=np.reshape(arr,(10,2))
arr2

array([[7, 2],
       [7, 5],
       [9, 9],
       [2, 1],
       [4, 2],
       [2, 7],
       [1, 7],
       [2, 5],
       [1, 5],
       [6, 6]])

In [39]:
arr3=np.reshape(arr,(3,3))

ValueError: cannot reshape array of size 20 into shape (3,3)

### iteration

In [41]:
#1D
a=np.array([1,2,3,4])
for i in a:
    print(i,end=" ")

1 2 3 4 

In [42]:
#2D
b=np.random.randint(1,9,size=(3,4))
print(b)

[[7 1 5 5]
 [6 7 1 1]
 [2 5 7 8]]


In [47]:
for row in b:
    for item in b.ravel():
        print(item,end=" ")

7 1 5 5 6 7 1 1 2 5 7 8 7 1 5 5 6 7 1 1 2 5 7 8 7 1 5 5 6 7 1 1 2 5 7 8 

In [45]:
#nditer
for i in np.nditer(a):
    print(i,end=" ")

1 2 3 4 

In [46]:
for i in np.nditer(b):
    print(i,end=" ")

7 1 5 5 6 7 1 1 2 5 7 8 

In [48]:
arr1d = np.random.randint(10, 40, size = (10, ))

print("Numpy Array: \n", arr1d)

print("Shape: ", arr1d.shape)

Numpy Array: 
 [23 37 29 15 19 21 39 15 20 11]
Shape:  (10,)


In [49]:
print("Original Array: ", arr1d)

for item in np.nditer(arr1d):
    if item > 20:
        item[...] = (item * 0)
        
print("Updated Array", arr1d)

Original Array:  [23 37 29 15 19 21 39 15 20 11]


ValueError: assignment destination is read-only

In [50]:
print("Original Array: ", arr1d)

for item in np.nditer(arr1d, op_flags=['readwrite']):
    if item > 20:
        item[...] = (item * 0)
        
print("Updated Array", arr1d)

Original Array:  [23 37 29 15 19 21 39 15 20 11]
Updated Array [ 0  0  0 15 19  0  0 15 20 11]


In [51]:
# Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all
#odd numbers with -1. (Using a Loop)
a=np.random.randint(1,20,size=(5,4))
print(a)

[[16  5  8  5]
 [19 14  4 14]
 [12 16  4  2]
 [ 2  1 17 17]
 [ 3 12 17  4]]


In [56]:
import numpy as np

# Generate a 5x4 array of random positive integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 4))

print("Original array:")
print(array)

# Update the array by replacing all odd numbers with -1 using a loop
for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        if array[i, j] % 2 != 0:
            array[i, j] = -1

print("\nUpdated array:")
print(array)


Original array:
[[16 93 11 32]
 [76 93 67 78]
 [30 50 42 40]
 [40 32 38 48]
 [ 3 16 34  3]]

Updated array:
[[16 -1 -1 32]
 [76 -1 -1 78]
 [30 50 42 40]
 [40 32 38 48]
 [-1 16 34 -1]]


In [57]:
#Given an array [1, -10, 2, 3, 0, 6], print the array in this order [0, 6, -10, 2, 1, 3]
array = [1, -10, 2, 3, 0, 6]

# Desired order of indices
order = [4, 5, 1, 2, 0, 3]

# Reorder the array based on the specified order
reordered_array = [array[i] for i in order]

# Print the reordered array
print(reordered_array)

[0, 6, -10, 2, 1, 3]


In [1]:
print(...)

Ellipsis


### Python operations on numpy array

In [2]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x+5)

[[ 6  7  8]
 [ 9 10 11]]


In [3]:
print(x-1)

[[0 1 2]
 [3 4 5]]


In [4]:
print(x%2)

[[1 0 1]
 [0 1 0]]


In [6]:
print(x*2)

[[ 2  4  6]
 [ 8 10 12]]


In [7]:
print(x<=3)

[[ True  True  True]
 [False False False]]


### Numpy maths

In [2]:
import numpy as np
print("Square Root: ", np.sqrt(4))

print("Exponent: ", np.exp(1))

print("Trigonometric Sin: ", np.sin(0))

print("Trigonometric Cos: ", np.cos(0))

print("... and many more")

Square Root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos:  1.0
... and many more


In [3]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Elementwise Addition: \n", np.add(x, y))

print("Elementwise Subtraction: \n", np.subtract(x, y))

print("Elementwise Multiplication: \n", np.multiply(x, y))

print("Elementwise Division: \n", np.divide(x, y))

Elementwise Addition: 
 [[ 6  8]
 [10 12]]
Elementwise Subtraction: 
 [[-4 -4]
 [-4 -4]]
Elementwise Multiplication: 
 [[ 5 12]
 [21 32]]
Elementwise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [4]:
# Matrix Multiplication
import numpy as np

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Matrix Multiplication (Way-1): \n", np.matmul(x, y))

print("Matrix Multiplication (Way-2): \n", np.dot(x, y))

print("Matrix Multiplication (Way-3): \n", x @ y)

Matrix Multiplication (Way-1): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-2): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-3): 
 [[19 22]
 [43 50]]


In [5]:
# Diagonal elements

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print("Diagonal: ", np.diag(x))

Original Array: 
 [[1 2 3]
 [4 5 6]]
Diagonal:  [1 5]


In [6]:
# Transpose of an array

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print()

print("Transpose: \n", x.T)

Original Array: 
 [[1 2 3]
 [4 5 6]]

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]


### Numpy statistics

In [8]:
x = np.array([[1,2], [3,4]])

print("Sum: ", np.sum(x))

print("Columnwise Sum: ", np.sum(x, axis=0)) # Column Wise

print("Rowwise Sum: ", np.sum(x, axis=1)) # Row wise

Sum:  10
Columnwise Sum:  [4 6]
Rowwise Sum:  [3 7]


In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Columnwise Minimum: ", np.min(x, axis=0)) # Column Wise

print("Rowwise Minimum: ", np.min(x, axis=1)) # Row wise

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Columnwise Minimum:  [1 2 3]
Rowwise Minimum:  [1 4]


In [10]:
x = np.array([160, 180, 146, 162, 184, 180])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [160 180 146 162 184 180]
Minimum:  146
Maximum:  184
Mean:  168.66666666666666
Median:  171.0
Variance:  187.55555555555557
Std Dev:  13.695092389449425


In [11]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))


Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Maximum:  6
Mean:  3.5
Median:  3.5
Variance:  2.9166666666666665
Std Dev:  1.707825127659933


In [12]:
heights = np.array([160, 180, 146, 162, 184, 180])

weights = np.array([50, 78, 45, 51, 80, 60])

np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

### Linspace

In [13]:
print(np.linspace(1,5,10))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [14]:
print(np.linspace(10, 13, 6))

[10.  10.6 11.2 11.8 12.4 13. ]


### Sorting

In [15]:
a=np.random.randint(1,20,size=(5,4))
print(a)
np.sort(a)

[[ 9 15  6  9]
 [13 19  8 14]
 [ 1  8 19 10]
 [ 2 11  6 10]
 [ 1 11  1 12]]


array([[ 6,  9,  9, 15],
       [ 8, 13, 14, 19],
       [ 1,  8, 10, 19],
       [ 2,  6, 10, 11],
       [ 1,  1, 11, 12]])

In [17]:
np.sort(a,axis=0)    #column wise sorting

array([[ 1,  8,  1,  9],
       [ 1, 11,  6, 10],
       [ 2, 11,  6, 10],
       [ 9, 15,  8, 12],
       [13, 19, 19, 14]])

In [19]:
np.sort(a,axis=1)     #row wise sorting

array([[ 6,  9,  9, 15],
       [ 8, 13, 14, 19],
       [ 1,  8, 10, 19],
       [ 2,  6, 10, 11],
       [ 1,  1, 11, 12]])

### Stacking

In [21]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(1,10,size=(2,3))
print(a)

[[7 5 6]
 [2 6 7]]


In [22]:
print(b)

[[3 9 9]
 [1 8 8]]


In [24]:
print(np.stack([a,b]))

[[[7 5 6]
  [2 6 7]]

 [[3 9 9]
  [1 8 8]]]


In [25]:
print(np.vstack([a,b]))

[[7 5 6]
 [2 6 7]
 [3 9 9]
 [1 8 8]]


In [26]:
print(np.hstack([a,b]))

[[7 5 6 3 9 9]
 [2 6 7 1 8 8]]


In [31]:
c=np.random.randint(1,10,size=(4,4))
print(c)

[[1 4 4 5]
 [8 5 9 4]
 [7 3 9 5]
 [4 2 3 6]]


In [33]:
print(np.vstack([a,c]))    #columns are not equal

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [35]:
print(np.hstack([a,c]))  #rows are not equal

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

###  concatenate

In [36]:
np.concatenate([a,b]) #axis=0

array([[7, 5, 6],
       [2, 6, 7],
       [3, 9, 9],
       [1, 8, 8]])

In [37]:
np.concatenate([a,b],axis=0)

array([[7, 5, 6],
       [2, 6, 7],
       [3, 9, 9],
       [1, 8, 8]])

In [38]:
np.concatenate([a,b],axis=1)

array([[7, 5, 6, 3, 9, 9],
       [2, 6, 7, 1, 8, 8]])

### Append

In [42]:
np.append(a,b,axis=0)

array([[7, 5, 6],
       [2, 6, 7],
       [3, 9, 9],
       [1, 8, 8]])

In [43]:
np.append(a,b,axis=1)

array([[7, 5, 6, 3, 9, 9],
       [2, 6, 7, 1, 8, 8]])

### Where

In [44]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [45]:
np.where(arr > 64, 0, 1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
np.where(arr > 64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])

In [47]:
#argsort
import numpy as np

arr = np.array([10, -5, 6, -1])

print("Indexes: ", arr.argsort()) # Returns indexes

print("Sorted Array: ", arr[arr.argsort()])

Indexes:  [1 3 2 0]
Sorted Array:  [-5 -1  6 10]


In [48]:
a=np.array([3,1,2,4])
print(a.argsort())

[1 2 0 3]


In [49]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]
